bugfix loading config & test code
kuoss/venti pull request #20
Opened 2023-04-04 13:48 UTC by jmnote

#### What this PR does / why we need it (변경 내용 / 필요성): 

현재 코드는 config load 단계에서 panic이 발생하는 버그가 있습니다. 포인터만 생성하고 실제 메모리 할당 과정이 없이 Unmarshal하기 때문인 것으로 보입니다. Unmarshal 전에 메모리를 할당해주어 panic을 방지합니다.

그리고 config_test.go에 TestLoad() 테스트 코드를 작성하였습니다.

#### Which issue(s) this PR fixes (관련 이슈):

#19 에 대응되며
#16 과도 관련이 있습니다.

#### Special notes for your reviewer (리뷰어에게 하고 싶은 말):

리뷰 감사합니다.

Unmarshal 전에 메모리를 할당해줍시다.
https://stackoverflow.com/questions/20478577/why-does-json-unmarshal-work-with-reference-but-not-pointer

Makefile는 checks(go fmt, vet, staticcheck, golangci-lint, test)가 병렬로 수행되던 것을 순차실행하기 위해 변경했습니다. (병렬 수행하면 어느 단계에서 메시지가 발생했는지 확인이 어려움)

pkg/handler/dashboard.go 는 변경한 것이 없는데 자동 교정되었어요.

#### Additional documentation, usage docs, etc. (기타 관련 문서, 사용법 등):

없음

2023-04-04 15:49 UTC, dozer-jang requested changes
말씀해주신 Unmarshal 에러는 loadYaml 함수 호출부분에서 & operator를 붙이지 않아서 발생한 문제입니다. 

그리고  포인터 타입의 변수를 초기화할 때
`var userConf *userConfig = &UserConfig{}` 보다는
`userConfig := &UserConfig{}` or `var userConf = &UserConfig{}` 이 간결할 것 같습니다.

2023-04-04 15:49 UTC, dozer-jang commented on pkg/configuration/config.go
>  	err = loadConfig(userConfigFile, userConf)
```suggestion
	err = loadConfig(userConfigFile, &userConf)
```
`loadConfig` 함수의 파라미터를 이렇게 수정해보시겠어요?

2023-04-04 15:49 UTC, dozer-jang commented on pkg/configuration/config.go
> -	err = loadConfig(dsConfigFile, &dataSourceConfig)
`dataSourceConfig`를 로드할때는 제대로 썼네요. 제가 userConfig 로드 코드에서 실수를 했네요.

2023-04-04 15:49 UTC, dozer-jang commented on pkg/configuration/config_test.go
> +	assert.Equal(t, cfg.DatasourcesConfig.Datasources[1], &Datasource{Type: "lethe", Name: "Lethe", URL: "http://lethe:3100", BasicAuth: false, BasicAuthUser: "", BasicAuthPassword: "", IsDefault: false
assert.Equal이 많은 것 같습니다. config 타입을 한번에 비교할 수 없을까요? `Datasource` 타입의 배열 때문에 비교가 힘든 걸까요?

2023-04-04 15:49 UTC, dozer-jang commented on pkg/configuration/config_test.go
> +	assert.Equal(t, cfg.DatasourcesConfig.Datasources[1], &Datasource{Type: "lethe", Name: "Lethe", URL: "http://lethe:3100", BasicAuth: false, BasicAuthUser: "", BasicAuthPassword: "", IsDefault: false
`Datasource`의 `Type`필드는 상수로 지정되어있습니다.

2023-04-04 15:49 UTC, dozer-jang commented on pkg/store/alertrulestore.go
>  		err = loadYaml(f, rg)
```suggestion
		err = loadYaml(f, &rg)
```

2023-04-04 16:41 UTC, jmnote commented on pkg/configuration/config.go
>  	err = loadConfig(userConfigFile, userConf)
제가 잘못 알고 있었네요. 포인터 변수라도 Unmarshal할 때는 &를 붙이는 게 맞고 이상 없네요.

2023-04-04 16:43 UTC, jmnote commented on pkg/configuration/config.go
> -	err = loadConfig(dsConfigFile, &dataSourceConfig)
수정했습니다.

2023-04-04 16:47 UTC, jmnote commented on pkg/configuration/config_test.go
> +	assert.Equal(t, cfg.DatasourcesConfig.Datasources[1], &Datasource{Type: "lethe", Name: "Lethe", URL: "http://lethe:3100", BasicAuth: false, BasicAuthUser: "", BasicAuthPassword: "", IsDefault: false
이 부분을 작성하면서 고민했던 부분인데... 포인터가 아니었다면 전체를 Equal 하나로 비교 가능한데, 포인터이기 때문에 값이 주소로 나오니까 Assert가 복잡해질 수밖에 없다는 생각이 들어요.

2023-04-04 16:50 UTC, jmnote commented on pkg/configuration/config_test.go
> +	assert.Equal(t, cfg.DatasourcesConfig.Datasources[1], &Datasource{Type: "lethe", Name: "Lethe", URL: "http://lethe:3100", BasicAuth: false, BasicAuthUser: "", BasicAuthPassword: "", IsDefault: false
테스트 코드에서는 굳이 상수까지 따질 필요는 없다고 생각되고요. 테스트코드는 표준적인 방법으로 최대한 간편하게 작성하는 게 좋고 생각해요.

예를 들어 일단 assert.Nil(t, cfg.DatasourcesConfig.Datasources[0]) 이런 테스트 코드를 대충 작성하고 실행하면 나오는 actual 값을 붙여넣는 방법이죠. 그렇게 하다보니까 "prometheus" 이런 값이 나온 것이고요.

2023-04-04 16:51 UTC, jmnote commented on pkg/store/alertrulestore.go
>  		err = loadYaml(f, rg)
이 부분도 변경하지 않을 이유는... 위에서 얘기한 바와 같습니다.

2023-04-04 18:53 UTC, jmnote commented
alertRuleStore는 관련해서는 그냥 &만 붙여서 되는 게 아니고, 구조적인 문제가 있었네요. 각 파일이 groups 를 가질 수 있고, 여러 개의 설정 파일이 있을 수 있긴 때문에 최종적으로 groupsList를 가지고 있어야 합니다.

2023-04-05 01:29 UTC, dozer-jang commented on pkg/configuration/config_test.go
> +	assert.Equal(t, cfg.DatasourcesConfig.Datasources[1], &Datasource{Type: "lethe", Name: "Lethe", URL: "http://lethe:3100", BasicAuth: false, BasicAuthUser: "", BasicAuthPassword: "", IsDefault: false
> 테스트 코드에서까지 굳이 상수명을 따질 필요는 없다고 생각되고요. 테스트코드는 표준적인 방법으로 최대한 간편하게 작성하는 게 좋다고 생각해요.


제가 상수라고만 말씀드렸지만 `DatasourceType` 이라는 alias 타입을 정의했기 때문에 `DatasourceType`의 `DatasourceTypePrometheus`가 더 좋을 것 같아서 말씀드렸어요.

> 
> 예를 들어 일단 assert.Nil(t, cfg.DatasourcesConfig.Datasources[0]) 이런 테스트 코드를 대충 작성하고 실행하면 나오는 actual 값을 붙여넣는 방법이죠. 그렇게 하다보니까 "prometheus" 이런 값이 나온 것이고요. assert는 결국 string으로 인식하여 비교하고 diff도 그렇게 알려주고 있고요.

2023-04-05 01:34 UTC, jmnote commented on pkg/configuration/config_test.go
> +	assert.Equal(t, cfg.DatasourcesConfig.Datasources[1], &Datasource{Type: "lethe", Name: "Lethe", URL: "http://lethe:3100", BasicAuth: false, BasicAuthUser: "", BasicAuthPassword: "", IsDefault: false
네 그러니까... 그것을 알지만 그것을 따르기보다는, 테스트 코드는 간편하게 표준적 방법으로 작성하는 것이 좋다고 본다는 의견이예요.

2023-04-05 01:36 UTC, dozer-jang commented
> alertRuleStore는 관련해서는 그냥 &만 붙여서 되는 게 아니고, 구조적인 문제가 있었네요. 각 파일이 groups 를 가질 수 있고, 여러 개의 설정 파일이 있을 수 있긴 때문에 최종적으로 groupsList를 가지고 있어야 합니다. 전체적으로 groupsList를 적용하고 테스트코드도 추가했습니다.

네 확인했습니다. 하나의 파일이 여러 group을 가질 수 있는 구조였네요. 감사합니다

2023-04-05 01:38 UTC, dozer-jang commented
`alertrRuleStore.go` 파일을 camel case로 변경하셨어요. golang에서 파일명에대한 컨벤션이 정해져있는 건 아니지만 전통적으로 표준 라이브러리들이 all lowercase로 작성되었고 venti도 all lowercase 이었기 때문에 기존 형식으로 변경 부탁드립니다.

https://github.com/golang/go/issues/36060#issuecomment-563625818

2023-04-05 01:48 UTC, dozer-jang commented
최초로 `DatasourceConfig` 필드의 `Datasource` 와 Service Discovery로 발견되는 `Datasource`가 동시에 쓰이고 있어서 포인터 타입으로 선언했던 것으로 기억합니다. 근데 말씀하신대로 생각해보니 너무 많은 포인터가 쓰이고 있네요.

```go
type Config struct {
	Version           string
	UserConfig        UsersConfig
	DatasourcesConfig DatasourcesConfig
}

...
        var userConf UsersConfig
	err = loadConfig(userConfigFile, &userConf)
	if err != nil {
		return nil, fmt.Errorf("error on loading User Config: %w", err)
        }
```

`UserConfig` 필드의 타입을 value타입으로 변경하면 좋을 것 같습니다.

Service Discovery 이후에 Datasources는 `DatasourceStore`에 따로 저장하고 있습니다.

2023-04-05 01:49 UTC, dozer-jang commented on .github/workflows/ci.yml
> +      run: go test ./... -v -coverprofile=coverage.out
race는 옵션을 제거하신 이유는 따로 있을까요?

2023-04-05 02:08 UTC, dozer-jang commented on pkg/configuration/config_test.go
> +	assert.Equal(t, cfg.DatasourcesConfig.Datasources[1], &Datasource{Type: "lethe", Name: "Lethe", URL: "http://lethe:3100", BasicAuth: false, BasicAuthUser: "", BasicAuthPassword: "", IsDefault: false
테스트 코드가 받은 output을 그대로 assert에 넣는다면 그것이 테스트 코드 작성의 의미가 있을까요? 그래도 테스트 코드가 있으니 형식 변경을 감지한다는 면에서는 기능하겠지만, 처음부터 우리의 논리의 코드 그대로 output이 나온다는 것을 확인할 수는 없을 것 같습니다. 

그리고 슬라이스의 비교의 경우 아래처럼 assert를 이용할 수도 있습니다. 말씀하신대로 입력 값이 변경되어도 대응이 간편합니다. 슬라이스 값들의 순서가 변경되어도, 값이 추가되어도 굳이 슬라이스의 길이를 확인하는 곳을 변경하지 않아도 되니까요. -> `assert.Equal(t, len(cfg.DatasourcesConfig.Datasources), 2)` 

단순히 간편하게 최종값을 그대로 넣어서 검사하는 것은 테스트 코드를 작성하는 것은 지양해야 합니다.

```go
assert.ElementsMatch(t, cfg.DatasourcesConfig.Datasources, []*Datasource{
		{Type: "prometheus", Name: "Prometheus", URL: "http://prometheus:9090", BasicAuth: false, BasicAuthUser: "", BasicAuthPassword: "", IsDefault: false, IsDiscovered: false},
		{Type: "lethe", Name: "Lethe", URL: "http://lethe:3100", BasicAuth: false, BasicAuthUser: "", BasicAuthPassword: "", IsDefault: false, IsDiscovered: false},
	})
```

2023-04-05 02:15 UTC, jmnote commented on .github/workflows/ci.yml
> +      run: go test ./... -v -coverprofile=coverage.out
ci.yml를 조정하는 김에 수정했는데... 특별한 이유가 있는 건 아니고... make checks와 일치시키려고 한 의도가 있었고... 애초에 저 명령어가 어딘가에서 가져온 건데, 옵션의 의미를 정확히 알기 전에는 기본값을 사용하는 게 좋겠다고 생각해서 뺐어요.

2023-04-05 02:28 UTC, dozer-jang commented on .github/workflows/ci.yml
> +      run: go test ./... -v -coverprofile=coverage.out
race condition detector가 golang에 기본적으로 탑재되어있어서 활성화 하는 옵션일거에요. 지금은 configuration이 file을 Read하는 경우가 밖에 없어서 괜찮을 것 같지만 테스트 수행 때는 항상 켜놓는게 일반적인 것 같더라구요.

2023-04-05 02:32 UTC, jmnote commented
> `alertrRuleStore.go` 파일을 camel case로 변경하셨어요. golang에서 파일명에대한 컨벤션이 정해져있는 건 아니지만 전통적으로 표준 라이브러리들이 all lowercase로 작성되었고 venti도 all lowercase 이었기 때문에 기존 형식으로 변경 부탁드립니다.
> 
> [golang/go#36060 (comment)](https://github.com/golang/go/issues/36060#issuecomment-563625818)

네, 좋은 지적입니다. helloworld.go, hello_world.go 이렇게 2가지 스타일로 작성하는 관례를 확인했습니다. 소문자로 작성하되 필요시 _를 사용해도 된다. 이 정도인 것 같네요. 우리 프로젝트에서는 type AlertRuleStore struct를 담은 파일의 경우 alert_rule_store.go 와 같은 형식을 사용하도록 일관적인 규칙을 부여해도 좋을 것 같습니다. 다만 이번 PR은 이미 사이즈가 크고, 전체 go파일을 일관성 있게 적용하는 것이 중요하므로 별도 issue로 처리하는 게 좋겠습니다.

2023-04-05 02:48 UTC, jmnote commented on pkg/configuration/config_test.go
> +	assert.Equal(t, cfg.DatasourcesConfig.Datasources[1], &Datasource{Type: "lethe", Name: "Lethe", URL: "http://lethe:3100", BasicAuth: false, BasicAuthUser: "", BasicAuthPassword: "", IsDefault: false
테스트 코드가 없는 것보다는 있는 게 나으니까, 빠른 개발을 위해 이 정도 편의성은 허용하고, 필요시 추후 개선해도 된다는 입장은 변함이 없지만, 궁극적으로는 말씀하신 방향이 맞다고 보고요. 말씀하신대로 수정했습니다.

2023-04-05 02:52 UTC, jmnote commented on .github/workflows/ci.yml
> +      run: go test ./... -v -coverprofile=coverage.out
그렇군요. -race 옵션을 추가하는 쪽으로 수정했습니다. make checks도 거기에 일치시켰어요.

2023-04-05 03:00 UTC, dozer-jang commented
> 최초로 `DatasourceConfig` 필드의 `Datasource` 와 Service Discovery로 발견되는 `Datasource`가 동시에 쓰이고 있어서 포인터 타입으로 선언했던 것으로 기억합니다. 근데 말씀하신대로 생각해보니 너무 많은 포인터가 쓰이고 있네요.
> 
> ```go
> type Config struct {
> 	Version           string
> 	UserConfig        UsersConfig
> 	DatasourcesConfig DatasourcesConfig
> }
> 
> ...
>         var userConf UsersConfig
> 	err = loadConfig(userConfigFile, &userConf)
> 	if err != nil {
> 		return nil, fmt.Errorf("error on loading User Config: %w", err)
>         }
> ```
> 
> `Config`타입의 `UserConfig` 필드의 타입을 value타입으로 변경하면 좋을 것 같습니다.
> 
> Service Discovery 이후에 `Datasources`는 `DatasourceStore`에 따로 저장하고 있습니다.

ping @jmnote

2023-04-05 03:17 UTC, jmnote commented
> 최초로 `DatasourceConfig` 필드의 `Datasource` 와 Service Discovery로 발견되는 `Datasource`가 동시에 쓰이고 있어서 포인터 타입으로 선언했던 것으로 기억합니다. 근데 말씀하신대로 생각해보니 너무 많은 포인터가 쓰이고 있네요.
> 
> ```go
> type Config struct {
> 	Version           string
> 	UserConfig        UsersConfig
> 	DatasourcesConfig DatasourcesConfig
> }
> 
> ...
>         var userConf UsersConfig
> 	err = loadConfig(userConfigFile, &userConf)
> 	if err != nil {
> 		return nil, fmt.Errorf("error on loading User Config: %w", err)
>         }
> ```
> 
> `Config`타입의 `UserConfig` 필드의 타입을 value타입으로 변경하면 좋을 것 같습니다.
> 
> Service Discovery 이후에 `Datasources`는 `DatasourceStore`에 따로 저장하고 있습니다.

수정했습니다.

2023-04-05 03:26 UTC, dozer-jang approved these changes
코드 확인했습니다. 의견 받아주셔서 정말 감사드립니다.
`Config` 타입의  `DatasourceConfig`도 value 타입으로 변경하면 좋을 것 같습니다. 하지만 datasourceStore 코드도 영향을 받으니 따로 이슈로 수정하는 것이 좋겠습니다.

다시 한번 감사드리고 approval합니다.

2023-04-05 03:34 UTC, jmnote commented
긴 내용 장시간 리뷰하느라 수고하셨습니다. 감사합니다. merge합니다.

2023-04-05 03:34 UTC, merged